# Generated by Django 5.2.1 on 2025-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Task_name', models.TextField(max_length=1000)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('task_updated', models.DateTimeField(auto_now=True)),
                ('task_due', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
